spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 7DOeV5odNyJd6JMdli4lgDBklsgFbkhv
            client-secret: ZufJg6Hsy8liUyLnqld_Y25hTlAai5Tm39pEpj9_02VYwNdiP73_pxZpGgOT_Qu2
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-pgobo3tr621jp6nd.us.auth0.com/